version: "3.8"

services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    networks:
      - mongo-network
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:6
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    networks:
      - mongo-network
    volumes:
      - mongo3_data:/data/db

  mongo-init:
    image: mongo:6
    container_name: mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-network
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 10 && mongosh --host mongo1:27017 /docker-entrypoint-initdb.d/init-mongo.js",
      ]

  scribble-api:
    build: .
    container_name: scribble-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo-init
    environment:
      MONGO_URI: "mongodb://admin:adminpassword@mongo1:27017,mongo2:27017,mongo3:27017/ADMIN_DB?authSource=admin&replicaSet=rs0"

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
