version: "3.8"

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/data/mongo-keyfile",
      ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo1_data:/data/db
      - ./mongo-keyfile:/data/mongo-keyfile:ro
    networks:
      - scribble_network

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/data/mongo-keyfile",
      ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo2_data:/data/db
      - ./mongo-keyfile:/data/mongo-keyfile:ro # Read-only keyfile
    networks:
      - scribble_network

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/data/mongo-keyfile",
      ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo3_data:/data/db
      - ./mongo-keyfile:/data/mongo-keyfile:ro # Read-only keyfile
    networks:
      - scribble_network

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint:
      [
        "bash",
        "-c",
        'sleep 20 && mongosh --host mongo1:27017 -u admin -p adminpassword --authenticationDatabase admin --eval ''rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongo1:27017" }, { _id: 1, host: "mongo2:27017" }, { _id: 2, host: "mongo3:27017" }]})''',
      ]

  networks:
    scribble_network:
      driver: bridge

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    volumes:
      - redis_data:/data

  scribble-api:
    build: .
    container_name: scribble-api
    mem_limit: 1.5g
    memswap_limit: 2g
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo-init
      - redis
    environment:
      MONGO_URI: "mongodb://admin:adminpassword@mongo1:27017,mongo2:27018,mongo3:27019/ADMIN_DB?authSource=admin&replicaSet=rs0"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  redis_data:
