version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: scribble-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db

  scribble-api:
    build: .
    container_name: scribble-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:adminpassword@scribble-mongo:27017/ADMIN_DB?authSource=admin"

volumes:
  mongodb_data:
