module.exports = {
  email: "sandeepb@acutedge.com",
  password: "Admin@123",
  firstName: "Sandeep",
  lastName: "Banga",
  scope: [
    "tenant.create",
    "tenant.read",
    "tenant.update",
    "tenant.delete",
    "admin.create",
    "admin.read",
    "admin.update",
    "admin.delete",
    "user.create",
    "user.read",
    "user.update",
    "user.delete",
    "role.create",
    "role.read",
    "role.update",
    "role.delete",
    "self.create",
    "self.read",
    "form.create",
    "form.read",
    "form.update",
    "form.delete",
    "visit.create",
    "visit.read",
    "visit.update",
    "visit.delete",
    "grid.create",
    "grid.read",
    "grid.update",
    "grid.delete",
  ],
};
