module.exports = {
  email: "sandeepb@acutedge.com",
  password: "Admin@123",
  scope: [
    "tenant.create",
    "tenant.read",
    "tenant.update",
    "tenant.delete",
    "admin.create",
    "admin.read",
    "admin.update",
    "admin.delete",
    "user.create",
    "user.read",
    "user.update",
    "user.delete",
    "role.create",
    "role.read",
    "role.update",
    "role.delete",
    "self.create",
    "self.read",
  ],
};
