module.exports = [
  {
    gridName: "clinicianTable",
    viewJson: {
      clinicianId: { isRequired: true, isVisible: true },
      firstName: { isRequired: true, isVisible: true },
      lastName: { isRequired: false, isVisible: true },
      age: { isRequired: false, isVisible: true },
      dob: { isRequired: false, isVisible: true },
      gender: { isRequired: false, isVisible: true },
      address1: { isRequired: false, isVisible: true },
      address2: { isRequired: false, isVisible: true },
      city: { isRequired: false, isVisible: true },
      state: { isRequired: false, isVisible: true },
      zip: { isRequired: false, isVisible: true },
      country: { isRequired: false, isVisible: true },
      primaryPhone: { isRequired: false, isVisible: true },
    },
  },
  {
    gridName: "clientTable",
    viewJson: {
      clientId: { isRequired: true, isVisible: true },
      clientGroupId: { isRequired: true, isVisible: true },
      firstName: { isRequired: true, isVisible: true },
      lastName: { isRequired: false, isVisible: true },
      age: { isRequired: false, isVisible: true },
      dob: { isRequired: false, isVisible: true },
      email: { isRequired: false, isVisible: true },
      gender: { isRequired: false, isVisible: true },
      address1: { isRequired: false, isVisible: true },
      address2: { isRequired: false, isVisible: true },
      city: { isRequired: false, isVisible: true },
      state: { isRequired: false, isVisible: true },
      zip: { isRequired: false, isVisible: true },
      country: { isRequired: false, isVisible: true },
      primaryPhone: { isRequired: false, isVisible: true },
      emergencyContact: { isRequired: false, isVisible: true },
      emergencyContactNo: { isRequired: false, isVisible: true },
    },
  },
  {
    gridName: "assessmentTable",
    viewJson: {
      clinicianId: { isRequired: true, isVisible: true },
      clientId: { isRequired: true, isVisible: true },
      assessmentFormId: { isRequired: true, isVisible: true },
      assessmentAnswer: { isRequired: true, isVisible: true, isUnique: true },
      s3Path: { isRequired: true, isVisible: true },
    },
  },
];
