module.exports = [
  {
    roleName: "user",
    scope: [
      "assessment.create",
      "assessment.read",
      "assessment.update",
      "assessment.delete",
      "answer.create",
      "answer.read",
      "answer.update",
      "answer.delete",
      "self.read",
      "self.update",
    ],
  },
  {
    roleName: "userAdmin",
    scope: [
      "admin.create",
      "admin.read",
      "admin.update",
      "admin.delete",
      "user.create",
      "user.read",
      "user.update",
      "user.delete",
      "role.create",
      "role.read",
      "role.update",
      "role.delete",
      "form.create",
      "form.read",
      "form.update",
      "form.delete",
      "self.read",
      "self.update",
      "grid.read",
      "grid.update",
    ],
  },
];
