name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Zip files
        run: zip -r my-function.zip . # Adjust if you want specific files

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.0.8 # Use appropriate version
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.FUNCTION_NAME }}
          zip_file: my-function.zip
